### ISSUE TITLE
AttributeError: module 'limesdr' has no attribute 'sink'

### ISSUE THREAD

**Issue by rodrirq** [myriadrf/gr-limesdr#78]
Hello, I have seen this post: https://github.com/myriadrf/gr-limesdr/issues/17 
Which seems to talk about the same problem.
I am working with GNU Radio 3.8 on PetaLinux 2020.2. I installed it via meta-sdr.
I have cross-compiled gr-limesdr and LimeSuite using PetaLinux SDK.
The thing is that when I try to run a simple flowgraph, I get this:

![Limesdr-sink](https://user-images.githubusercontent.com/80888874/123938735-a9621a80-d997-11eb-8a60-03d602c92caf.png)

I modified the `__init__.py` to see the error vi removing the try / except block and got this:

![Screenshot from 2021-06-29 12-49-18](https://user-images.githubusercontent.com/80888874/123939059-065dd080-d998-11eb-85b1-dc6bd6a6dad4.png)

I asked this on the myriadrf forum, but I will ask it here as well, just in case.
